// Maps Hevy exercise titles to a primary muscle group.
// This is the same mapping used to analyze your Hevy CSV export earlier —
// extend it as you add new exercises to your routines.
export const MUSCLE_MAP: Record<string, string> = {
  "Ab Wheel": "abs",
  "Around The World": "shoulders",
  "Back Extension (Machine)": "lower_back",
  "Back Extension (Weighted Hyperextension)": "lower_back",
  "Behind the Back Curl (Cable)": "biceps",
  "Behind the Back Wrist Curl (Barbell)": "forearms",
  "Bench Dip": "triceps",
  "Bench Press (Barbell)": "chest",
  "Bench Press (Cable)": "chest",
  "Bench Press (Smith Machine)": "chest",
  "Bench Press - Close Grip (Barbell)": "triceps",
  "Bent Over Row (Barbell)": "back",
  "Bent Over Row (Dumbbell)": "back",
  "Bulgarian Split Squat (Dumbbell)": "quads",
  "Butterfly (Pec Deck)": "chest",
  "Cable Crunch": "abs",
  "Cable Fly Crossovers": "chest",
  "Cable Squat": "quads",
  "Calf Extension (Machine)": "calves",
  "Calf Press (Machine)": "calves",
  "Chest Dip": "chest",
  "Chest Fly (Band)": "chest",
  "Chest Fly (Dumbbell)": "chest",
  "Chest Fly (Machine)": "chest",
  "Chest Press (Machine)": "chest",
  "Concentration Curl": "biceps",
  "Cross Body Hammer Curl": "biceps",
  "Crunch (Machine)": "abs",
  "Crunch (Weighted)": "abs",
  "Curtsy Lunge (Dumbbell)": "quads",
  "Deadlift (Barbell)": "back",
  "Deadlift (Smith Machine)": "back",
  "Decline Bench Press (Machine)": "chest",
  "Drag Curl": "biceps",
  "Dumbbell Row": "back",
  "EZ Bar Biceps Curl": "biceps",
  "Face Pull": "shoulders",
  "Front Raise (Barbell)": "shoulders",
  "Front Raise (Cable)": "shoulders",
  "Front Raise (Dumbbell)": "shoulders",
  "Goblet Squat": "quads",
  "Hack Squat (Machine)": "quads",
  "Hammer Curl (Cable)": "biceps",
  "Hammer Curl (Dumbbell)": "biceps",
  "Hip Abduction (Machine)": "glutes",
  "Hip Adduction (Machine)": "glutes",
  "Hip Thrust (Barbell)": "glutes",
  "Incline Bench Press (Dumbbell)": "chest",
  "Incline Bench Press (Smith Machine)": "chest",
  "Incline Chest Fly (Dumbbell)": "chest",
  "Incline Chest Press (Machine)": "chest",
  "Iso-Lateral Chest Press (Machine)": "chest",
  "Iso-Lateral High Row (Machine)": "back",
  "Iso-Lateral High Row Wide": "back",
  "Iso-Lateral Low Row": "back",
  "Iso-Lateral Row (Machine)": "back",
  "Kelso Shrug": "back",
  "Lat Pulldown (Band)": "back",
  "Lat Pulldown (Cable)": "back",
  "Lat Pulldown (Machine)": "back",
  "Lat Pulldown - Close Grip (Cable)": "back",
  "Lateral Raise (Cable)": "shoulders",
  "Lateral Raise (Dumbbell)": "shoulders",
  "Lateral Raise (Machine)": "shoulders",
  "Leg Curl Unilateral": "hamstrings",
  "Leg Extension (Machine)": "quads",
  "Leg Press (Machine)": "quads",
  "Leg Press Horizontal (Machine)": "quads",
  "Low Cable Fly Crossovers": "chest",
  "Lunge (Barbell)": "quads",
  "Lunge (Dumbbell)": "quads",
  "Lying Leg Curl (Machine)": "hamstrings",
  "Lying Leg Raise": "abs",
  "Overhead Curl (Cable)": "biceps",
  "Overhead Press (Barbell)": "shoulders",
  "Overhead Press (Dumbbell)": "shoulders",
  "Overhead Press (Smith Machine)": "shoulders",
  "Pendlay Row (Barbell)": "back",
  "Pendulum Squat (Machine)": "quads",
  "Plank": "abs",
  "Preacher Curl (Barbell)": "biceps",
  "Pull Up": "back",
  "Pull Up (Assisted)": "back",
  "Pull Up (Weighted)": "back",
  "Push Up": "chest",
  "Rear Delt Reverse Fly (Cable)": "shoulders",
  "Rear Delt Reverse Fly (Dumbbell)": "shoulders",
  "Rear Delt Reverse Fly (Machine)": "shoulders",
  "Rear Kick (Machine)": "glutes",
  "Reverse Curl (Barbell)": "biceps",
  "Reverse Grip Lat Pulldown (Cable)": "back",
  "Reverse Lunge (Barbell)": "quads",
  "Romanian Deadlift (Barbell)": "hamstrings",
  "Romanian Deadlift (Dumbbell)": "hamstrings",
  "Rope Straight Arm Pulldown": "back",
  "Running": "cardio",
  "Russian Twist (Weighted)": "abs",
  "Seated Cable Row - Bar Grip": "back",
  "Seated Cable Row - Bar Wide Grip": "back",
  "Seated Calf Raise": "calves",
  "Seated Chest Flys (Cable)": "chest",
  "Seated Dip Machine": "triceps",
  "Seated Incline Curl (Dumbbell)": "biceps",
  "Seated Lateral Raise (Dumbbell)": "shoulders",
  "Seated Leg Curl (Machine)": "hamstrings",
  "Seated Overhead Press (Dumbbell)": "shoulders",
  "Seated Palms Up Wrist Curl": "forearms",
  "Seated Row (Machine)": "back",
  "Seated Shoulder Press (Machine)": "shoulders",
  "Shoulder Press (Dumbbell)": "shoulders",
  "Shrug (Dumbbell)": "back",
  "Shrug (Machine)": "back",
  "Single Arm Cable Row": "back",
  "Single Arm Curl (Cable)": "biceps",
  "Single Arm Lat Pulldown": "back",
  "Single Arm Lateral Raise (Cable)": "shoulders",
  "Single Arm Triceps Pushdown (Cable)": "triceps",
  "Single Leg Standing Calf Raise (Barbell)": "calves",
  "Skullcrusher (Barbell)": "triceps",
  "Skullcrusher Machine": "triceps",
  "Spider Curl (Barbell)": "biceps",
  "Spider Curl (Dumbbell)": "biceps",
  "Split Squat (Dumbbell)": "quads",
  "Squat (Barbell)": "quads",
  "Squat (Smith Machine)": "quads",
  "Squat Row": "back",
  "Standing Calf Raise (Barbell)": "calves",
  "Standing Calf Raise (Smith)": "calves",
  "Standing Leg Curls": "hamstrings",
  "T Bar Row": "back",
  "Treadmill": "cardio",
  "Triceps Dip": "triceps",
  "Triceps Dip (Weighted)": "triceps",
  "Triceps Extension (Barbell)": "triceps",
  "Triceps Extension (Cable)": "triceps",
  "Triceps Extension (Dumbbell)": "triceps",
  "Triceps Kickback (Cable)": "triceps",
  "Triceps Kickback (Dumbbell)": "triceps",
  "Triceps Pushdown": "triceps",
  "Triceps Rope Pushdown": "triceps",
  "Unilateral Hammer Curl Cable": "biceps",
  "Walking": "cardio",
  "Warm Up": "other",
  "Wrist Roller": "forearms",
};

export function muscleFor(title: string): string {
  return MUSCLE_MAP[title] ?? "other";
}
